version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/api
    ports:
      - "80:80"
    depends_on:
      - mongodb_container

volumes:
  mongodb_data_container: