# Generated by Django 2.1.15 on 2020-03-30 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [migrations.CreateModel(name='Event',
                                         fields=[('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4)),
                                                 ('start_time', models.TimeField()),
                                                 ('finish_time', models.TimeField()),
                                                 ('name', models.CharField(max_length=50, blank=False, default='')), (
                                                     'description',
                                                     models.CharField(max_length=200, blank=False, default='')),
                                                 ('image', models.CharField(max_length=200, blank=False, default='')),
                                                 ('user', models.CharField(max_length=200, blank=False, default='')),
                                                 ('guest_count', models.IntegerField()), ('provincia', models.CharField(
                                                 max_length=200, blank=False, default='')),
                                                 ('canton', models.CharField(max_length=200, blank=False, default='')),
                                                 ('area', models.JSONField()), ('services', models.JSONField()),
                                                 ('is_active', models.BooleanField(default=True))]),

        migrations.CreateModel(name='Payment', fields=[('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4)),
                                                       ('user', models.UUIDField()), ('event', models.UUIDField()),
                                                       ('service', models.UUIDField()),
                                                       ('amount', models.IntegerField()),
                                                       ('payment_date', models.DateField())]),

        migrations.CreateModel(name='Product', fields=[('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4)),
                                                       ('service', models.UUIDField()), ('name',
                                                                                         models.CharField(max_length=50,
                                                                                                          blank=False,
                                                                                                          default='')),
                                                       ('description',
                                                        models.CharField(max_length=200, blank=False, default='')),
                                                       ('price', models.IntegerField()),
                                                       ('is_active', models.BooleanField(default=True)), ('image',
                                                                                                          models.CharField(
                                                                                                              max_length=200,
                                                                                                              blank=False,
                                                                                                              default='')),
                                                       ('rate_type',
                                                        models.CharField(max_length=200, blank=False, default=''))]),
        migrations.CreateModel(name='Provider',
                               fields=[('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4)),
                                       ('user', models.UUIDField()),
                                       ('company_name', models.CharField(max_length=200, blank=False, default='')),
                                       ('subscription', models.JSONField())]),
        migrations.CreateModel(name='Subscription',
                               fields=[('initial_date', models.DateField()), ('rate', models.IntegerField()),
                                       ('plan_name', models.CharField(max_length=200, blank=False, default='')),
                                       ('allowed_services_count', models.IntegerField()),
                                       ('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='Service', fields=[('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4)),
                                                       ('provider', models.UUIDField()), ('name', models.CharField(
                max_length=200, blank=False, default='')), ('description',
                                                            models.CharField(max_length=200, blank=False, default='')),
                                                       ('type',
                                                        models.CharField(max_length=200, blank=False, default='')), (
                                                       'image',
                                                       models.CharField(max_length=200, blank=False, default='')), (
                                                           'provincia',
                                                           models.CharField(max_length=200, blank=False, default='')), (
                                                       'canton',
                                                       models.CharField(max_length=200, blank=False, default='')),
                                                       ('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='User', fields=[('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4)), (
        'email', models.CharField(max_length=200, blank=False, default='')),
                                                    ('name', models.CharField(max_length=200, blank=False, default='')),
                                                    ('type', models.CharField(max_length=200, blank=False, default='')),
                                                    (
                                                    'phone', models.CharField(max_length=200, blank=False, default='')),
                                                    (
                                                    'image', models.CharField(max_length=200, blank=False, default='')),
                                                    ('is_active', models.BooleanField(default=True))])]
